version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install curl
          command: npm install -y curl
      - run:
          name: Install dependencies
          command: npm install
  run-e2e-tests:
    docker:
     - image: cypress/base:latest
    environment:
      MONGODB_URI: mongodb+srv://lhetland:rootROOT@cluster0.aysiw.mongodb.net/wordGuessTest?retryWrites=true&w=majority&appName=Cluster0
    steps:
      - checkout
      - run:
          name: Install curl
          command: apt-get update && apt-get install -y curl
      - run:
          name: Install dependencies
          command: npm install
      - run: 
          name: Start start-server
          command: npm run start
      - run:
          name: Run Cypress E2E tests
          command: npx wait-on@latest http://localhost:3000 && npx cypress run --browser electron --headless
      
      

workflows:
  run-tests:
    jobs:
      - start-server
      - run-e2e-tests:
          requires:
            - start-server