version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  custom-run-tests:
    docker:
      - image: cypress/base:16  # Cypress-compatible image
    environment:
      MONGODB_URI: mongodb+srv://lhetland:rootROOT@cluster0.aysiw.mongodb.net/wordGuessTest?retryWrites=true&w=majority&appName=Cluster0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - cypress/run:
          name: run-e2e-tests
          requires:
            - custom-run-tests
          cypress-command: npm run start && npx cypress run --browser electron --headless

workflows:
  run-tests:
    jobs:
      - custom-run-tests
      
