version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server-and-run-tests:
    docker:
      - image: cypress/base:latest
    environment:
      MONGODB_URI: mongodb+srv://lhetland:rootROOT@cluster0.aysiw.mongodb.net/wordGuessTest?retryWrites=true&w=majority&appName=Cluster0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start server
          command: npm run start &
      - run:
          name: Wait for server to start
          command: npx wait-on@latest http://localhost:3001
      - run:
          name: Run Cypress E2E tests
          command: npx cypress run --browser electron --headless

workflows:
  run-tests:
    jobs:
      - start-server-and-run-tests