version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  custom-run-tests:
    docker:
      - image: cypress/base:16  # Cypress-compatible image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start the application
          command: npm run start:dev &
      - run:
          name: Wait for the server to start
          command: npx wait-on http://localhost:3000
      - cypress/run:
          browser: electron
          headless: true

workflows:
  run-tests:
    jobs:
      - custom-run-tests