version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
  run-e2e-tests:
    docker:
     - image: cypress/base:latest
    environment:
      MONGODB_URI: mongodb+srv://lhetland:rootROOT@cluster0.aysiw.mongodb.net/wordGuessTest?retryWrites=true&w=majority&appName=Cluster0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress E2E tests
          command: npm run start:dev && npx cypress run --browser electron --headless

workflows:
  run-tests:
    jobs:
      - start-server
      - run-e2e-tests:
          requires:
            - start-server
  
          # Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
          