version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  custom-run-tests:
    docker:
      - image: cypress/base:16  # Cypress-compatible image
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start the application
          command: npm run start:dev &
      - run:
          name: Check server logs
          command: |
            echo "Waiting a few seconds for the server to start..."
            sleep 5  # Give it a moment to start
            echo "Checking server status"
            curl http://localhost:3000 || echo "Server is not running yet"  # Check if the server is accessible
      - run:
          name: Wait for the server to start
          command: npx wait-on http://localhost:3000

workflows:
  run-tests:
    jobs:
      - custom-run-tests
      - cypress/run:
          name: run-e2e-tests
          requires:
            - custom-run-tests
          cypress-command: npx cypress run --browser electron --headless
