version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

workflows:
  run-tests:
    jobs:
      - cypress/run:
          name: run-e2e-tests
          cypress-command: npx wait-on@latest http://localhost:3000 && npx cypress run --browser electron --headless
          start-command: npm run start:dev
          # Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
          
          