version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  custom-run-tests:
    docker:
      - image: cypress/base:16  # Cypress-compatible image
    environment:
      MONGODB_URI: mongodb+srv://lhetland:rootROOT@cluster0.aysiw.mongodb.net/wordGuessTest?retryWrites=true&w=majority&appName=Cluster0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start the application
          command: npm run start:dev &  # Start the server in the background
      - run:
          name: Wait for the server to start
          command: npx wait-on http://localhost:3000 --timeout 60000  # Adjust port as necessary

  run-e2e-tests:
    docker:
      - image: cypress/base:16  # Cypress-compatible image
    environment:
      MONGODB_URI: mongodb+srv://lhetland:rootROOT@cluster0.aysiw.mongodb.net/wordGuessTest?retryWrites=true&w=majority&appName=Cluster0
    steps:
      - checkout
      - run:
          name: Run Cypress tests
          command: npx cypress run --browser electron --headless

workflows:
  run-tests:
    jobs:
      - custom-run-tests
      - run-e2e-tests:
          requires:
            - custom-run-tests
