version: 2.1

# orbs:
#   cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
        docker:
          - image: cypress/base:latest
        # environment:
        #   MONGODB_URI: mongodb+srv://lhetland:rootROOT@cluster0.aysiw.mongodb.net/wordGuessTest?retryWrites=true&w=majority&appName=Cluster0
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm install
          - run:
              name: Install specific packages
              command: npm install concurrently wait-on
          - run:
              name: Run e2e tests
              command: |
                npm run circleci-run
                if [ $? -eq 0 ]; then
                  echo "Tests passed! Exiting job."
                  exit 0
                else
                  echo "Tests failed. Exiting with error."
                  exit 1
                fi
          # - run:
          #     name: Stop any lingering processes
          #     command: |
          #       jobs -p | xargs kill || true  # Kill any remaining background jobs if they exist
            

workflows:
  run-tests:
    jobs:
      - start-server
      
          # Make sure to add MONGODB_URI to ENVIRONMENT VARIABLES in CircleCI so that the tests can connect to the database
          
          